# -- Start TokyoNight Alacritty Colors --

[[colors.indexed_colors]]
color = "0xff9e64"
index = 16

[[colors.indexed_colors]]
color = "0xdb4b4b"
index = 17

[colors.bright]
black = "0x414868"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[colors.normal]
black = "0x15161e"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"

[colors.primary]
background = "0x1a1b26"
foreground = "0xc0caf5"

# -- End TokyoNight Alacritty Colors --

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
family = "JetBrainsMono NFM"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NFM"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NFM"
style = "Italic"

[font.normal]
family = "JetBrainsMono NFM"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
opacity = 1.0
option_as_alt = "Both"

[window.padding]
x = 10
y = 8
